#!/bin/ksh

[ $# -eq 0 ] && echo "usage: $0 name" && exit 1

grep -i -s "$*" phone-book
status=$?
[ $status -eq 1 ] && echo "Noone named \"$*\" in the phone book" && exit 1
[ $status -eq 2 ] && echo "Missing phone book" && exit 1

exit 0
