#!/bin/ksh

# newcal :  Nice interface to /bin/cal

case $# in
0) set `date`; m=$2; y=$6 ;;		# no arguments; use today
1) y=$1; set `date`; m=$2 ;;		# 1 argument; use this year
2) m=$1; y=$2 ;;			# 2 arguments; month and year
*) echo "Too many arguments to $0" ;
   echo "Aborting ..." ;
   exit 1 ;;
esac

case $m in
[jJ]an* ) m=1 ;;
[fF]eb* ) m=2 ;;
[mM]ar* ) m=3 ;;
[aA]pr* ) m=4 ;;
[mM]ay* ) m=5 ;;
[jJ]un* ) m=6 ;;
[jJ]ul* ) m=7 ;;
[aA]ug* ) m=8 ;;
[sS]ep* ) m=9 ;;
[oO]ct* ) m=10 ;;
[nN]ov* ) m=11 ;;
[dD]ec* ) m=12 ;;
[1-9] | 0[1-9] | 1[0-2] ) ;;		# numeric month
*) 
esac

/bin/cal $m $y

exit
