#!/bin/ksh

pid="$$"
procname=$0
uid=`id | sed 's/[^=]*=\([0-9][0-9]*\).*/\1/'`

filename="$0_$pid_$uid"
echo $filename

arg=$1
if [ $arg -lt 10 ]
then
    number=00$arg
elif [ $arg -lt 100 ]
then
    number=0$arg
else
    number=$arg
fi

echo $number
