#!/bin/ksh

trap "echo $0 aborted by user ; exit 1" 2 15

if [ $# -eq 0 ]
then
    echo "usage: $0 username"
    exit 1
fi

while sleep 5
do
    if who | grep -s $1 > /dev/null
    then
	echo "$1 is logged in now"
	break
    else
	echo "$1 is not here yet"
    fi
done
