
checkeven:	main.o functions.o
	gcc -o checkeven main.o functions.o

main.o:	main.c
	gcc -g -c main.c

functions.o:	functions.c
	gcc -g -c functions.c

fullclean:
	/bin/rm checkeven *.o

clean:
	/bin/rm *.o
